version: "3.8"

services:
  whiteboard_server:
    image: "meeting/whiteboard-server"
    ports:
      - "3101:3101"
    environment:
      - "URL_MONGO=mongodb://room:aaaa1234@172.24.106.203:27017/room?maxPoolSize=20&w=majority"
      - "PORT=3101"

volumes:
  notused:
